name = "ftools"
version = "0.0.1"
license = "BSD"
author = "Federico E. Benelli"
maintainer = "federico.benelli@mi.unc.edu.ar"
copyright = "Copyright 2022, Jane Doe"
[build]
auto-executables = false
auto-tests = false
auto-examples = false
[install]
library = true
