name = "ftools"
version = "0.0.3"
license = "BSD"
author = "Federico E. Benelli"
maintainer = "federico.benelli@mi.unc.edu.ar"
copyright = "Copyright 2023, Federico E. Benelli"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false
